testproject/demo/urls.py
from django.conf.urls import patterns, include, url

from . import views

urlpatterns = patterns('',
    url('^$', views.main, name='demo_main'),
)

testproject/testproject/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    ('^', include('simpleselect.urls')),
    ('^', include('demo.urls')),
)

testproject/demo/models.py
from django.db import models


class Company(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Person(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    company = models.ForeignKey(Company)

    def __str__(self):
        return "{} {} ({})".format(self.first_name, self.last_name,
                                   self.company)

testproject/demo/forms.py
from django import forms
import simpleselect

from . import models


class PersonField(simpleselect.AutoSelectField):

    queries = ['first_name__icontains', 'last_name__icontains']

    data = models.Person.objects.all()


class AddEmployeeForm(forms.Form):
    """Really just a farce that lets me play with a different field."""

    person = PersonField(initial=10, help_text="Should have an initial value.")


class CompanyField(simpleselect.AutoSelectField):

    queries = ['name__icontains']

    data = models.Company.objects.all()


class PersonForm(forms.ModelForm):

    company = CompanyField()

    class Meta:
        model = models.Person

testproject/demo/views.py
# Create your views here.
import django.shortcuts as django

from . import forms


def main(request):
    """Show two unsubmittable test forms."""
    context = {
        'form': forms.PersonForm(),
        'form2': forms.AddEmployeeForm(),
    }

    return django.render(request, "demo/form.django.html", context)

testproject/demo/templates/demo/form.django.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
    <head>
        <title>Add a Person</title>

        <link rel="stylesheet" type="text/css"
        href="{% static 'bootstrap/dist/css/bootstrap.css' %}">

        <link rel="stylesheet" type="text/css"
        href="{% static 'selectize/dist/css/selectize.bootstrap3.css' %}">

    </head>

    <body>
        <h1>Test forms</h1>
        <p>None of these forms submit, they just have autocomplete fields.</p>
        <h2>Add a new Person</h1>
        <form>
            {{ form.as_p }}
            <h3>Testing butons</h3>
            <p>Set company ID to <input id="newcompanyid" class="idfield" value="1">: <input type="submit" id="companybutton" value="Set"></p>
        </form>
        <h2>Add something that has a Person field</h2>
        <form>
            {{ form2.as_p }}
            <h3>Testing butons</h3>
            <p>Set person ID to <input id="newpersonid" class="idfield" value="1">: <input type="submit" id="personbutton" value="Set"></p>
        </form>
        <script src="{% static 'jquery/jquery.min.js' %}" type="text/javascript"></script>
        <script src="{% static 'bootstrap/dist/js/bootstrap.min.js' %}" 
            type="text/javascript"></script>
        <script src="{% static 'selectize/dist/js/standalone/selectize.min.js' %}" 
            type="text/javascript"></script>
        <script src="{% static 'simpleselect.js' %}" type="text/javascript"></script>
        <script language="javascript">
            $(function() {
                $("#companybutton").click(function(evt) {
                    evt.preventDefault();
                    $("#id_company").val($("#newcompanyid").val()).trigger('change');
                });
            });
        </script>
        <script language="javascript">
            $(function() {
                $("#personbutton").click(function(evt) {
                    evt.preventDefault();
                    $("#id_person").val($("#newpersonid").val()).trigger('change');
                });
            });
        </script>
    </body>
</html>